server:
  port: 8761

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://xn--d1ab2a.space/auth/realms/edo-project-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: edo-project-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://xn--d1ab2a.space/auth/realms/edo-project-realm
            user-name-attribute: preferred_username
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    username: "guest"
    password: "guest"
    host: "localhost"
    virtual-host: "/"
    port: "5672"
    template:
      routing-key: "common"
      default-receive-queue: "common"
      reply-timeout: 10000

jwt:
  auth:
    converter:
      resource-id: edo-project-client
      principle-attribute: preferred_username

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  dashboard:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info
springdoc:
  swagger-ui:
    path: /swagger
