spring:
  application:
    name: edo-scheduler
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    username: "guest"
    password: "guest"
    host: "localhost"
    virtual-host: "/"
    port: "5672"
    template:
      routing-key: "scheduler"
      default-receive-queue: "scheduler"
      reply-timeout: 10000

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
# Конфигурация для получения данных из внешнего хранилища
job:
  schedule:
    cron: "0 0 * * * *" # Расписание выполнения задачи (каждый час)
    cron_delete_old_files: "0 0 0 * * *" # Расписание выполнения задачи (каждый день в полночь)
external:
  storage:
    url: "http://xn--d1ab2a.space/mock/employees" # Адрес внешнего хранилища данных