
#docker-compose up
version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"