yandex:
  geo:
    url: https://geocode-maps.yandex.ru/1.x/?format=json&results=1&sco=longlat&apikey=9fdbb2aa-5f75-43e0-ae21-491b46864d11&geocode=
spring:
  flyway:
    enabled: true
    user: postgres
    password: oog
    url: jdbc:postgresql://localhost:5432/edo_db?currentSchema=${spring.flyway.default-schema}
    default-schema: edo-2
    locations: db/migration
    out-of-order: true
  jpa:
    properties:
      hibernate:
        default_schema: edo-2
  application:
    name: edo-service
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    username: "guest"
    password: "guest"
    host: "localhost"
    virtual-host: "/"
    port: "5672"
    template:
      routing-key: "service"
      default-receive-queue: "service"
      reply-timeout: 10000
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    enable-self-preservation: false
management:
  endpoints:
    web:
      exposure:
        include: info
springdoc:
  swagger-ui:
    path: /swagger