spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: edo.2.kate@gmail.com
    password: uatadagugdrawmbl

    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: false
          starttls:
              enable: true
  application:
    name: edo-integration
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    username: "guest"
    password: "guest"
    host: "localhost"
    virtual-host: "/"
    port: "5672"
    template:
      routing-key: "integration"
      default-receive-queue: "integration"
      reply-timeout: 10000
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: info
springdoc:
  swagger-ui:
    path: /swagger