spring:
  mail:
    host: "app.debugmail.io"
    port: 25
    username: "46d9d802-c701-4a6b-81b0-f644aad9abec"
    password: "97340181-f6e0-4e5b-bb23-ca7a900248c9"
    protocol: smtp
    properties.mail.smtp:
      auth: true
      ssl: false
  application:
    name: edo-integration
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    username: "guest"
    password: "guest"
    host: "localhost"
    virtual-host: "/"
    port: "5672"
    template:
      routing-key: "integration"
      default-receive-queue: "integration"
      reply-timeout: 10000
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: info
springdoc:
  swagger-ui:
    path: /swagger