spring:
  mail:
    host: "app.debugmail.io"
    port: 25
    username: "a5ae3681-2cee-4604-b9e1-1c31e8fdba67"
    password: "d71639cd-4d78-4344-af83-ddeb90f46c6c"
    protocol: smtp
    properties.mail.smtp:
      auth: true
      ssl: false
  application:
    name: edo-integration
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    username: "guest"
    password: "guest"
    host: "localhost"
    virtual-host: "/"
    port: "5672"
    template:
      routing-key: "integration"
      default-receive-queue: "integration"
      reply-timeout: 10000
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: info
springdoc:
  swagger-ui:
    path: /swagger