spring:
  application:
    name: edo-file-storage
  servlet:
    multipart:
      max-file-size: 20MB # Максимальный размер каждого файла, который может быть загружен в мультипартном запросе
      max-request-size: 20MB # Максимальный размер всего мультипартного запроса, включая все его файлы и другие данные
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: info
springdoc:
  swagger-ui:
    path: /swagger
minio: # Конфигурация MinIO сервера
  endpoint: http://localhost:9000  # Адрес MinIO сервера
  accessKey: username  # Ключ доступа к MinIO (логин)
  secretKey: password  # Секретный ключ MinIO (пароль)
  bucketName: bucket  # Имя бакета, в котором будут храниться файлы