spring:
  application:
    name: edo-file-storage
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    username: "guest"
    password: "guest"
    host: "localhost"
    virtual-host: "/"
    port: "5672"
    template:
      routing-key: "storage"
      default-receive-queue: "storage"
      reply-timeout: 10000
  servlet:
    multipart:
      max-file-size: 20MB # Максимальный размер каждого файла, который может быть загружен в мультипартном запросе
      max-request-size: 20MB # Максимальный размер всего мультипартного запроса, включая все его файлы и другие данные
minio: # Конфигурация MinIO сервера
  endpoint: http://localhost:9000  # Адрес MinIO сервера
  accessKey: username  # Ключ доступа к MinIO (логин)
  secretKey: password  # Секретный ключ MinIO (пароль)
  bucketName: bucket  # Имя бакета, в котором будут храниться файлы
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: info
springdoc:
  swagger-ui:
    path: /swagger